version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
        - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    links:
      - database
  database:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=database"
    ports:
      - "33061:3306"
    volumes:
      - ./.data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - "6382:6379"
