name: Laravel

on: [push, pull_request]

jobs:
  tests:
    services:
        mysql:
            image: mysql:5.7
            env:
                MYSQL_ALLOW_EMPTY_PASSWORD: yes
                MYSQL_DATABASE: database_test
            ports:
                - 3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

      
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: 7.4
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, soap, intl
        coverage: none

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Copy .env
      run: php -r "copy('src/Framework/.env.testing', 'src/Framework/.env');"
      
    - name: Run migrations
      run: php artisan migrate --no-interaction --force
        
    - name: Execute tests
      run: vendor/bin/phpunit
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      
